export const FETCH_POLLS_REQUEST = 'FETCH_POLLS_REQUEST';
export const FETCH_POLLS_SUCCESS = 'FETCH_POLLS_SUCCESS';
export const FETCH_POLLS_FAILURE = 'FETCH_POLLS_FAILURE';

export const CREATE_POLL_REQUEST = 'CREATE_POLL_REQUEST';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const CREATE_POLL_FAILURE = 'CREATE_POLL_FAILURE';

export const VOTE_POLL_REQUEST = 'VOTE_POLL_REQUEST';
export const VOTE_POLL_SUCCESS = 'VOTE_POLL_SUCCESS';
export const VOTE_POLL_FAILURE = 'VOTE_POLL_FAILURE';

export const FETCH_POLL_RESULTS_REQUEST = 'FETCH_POLL_RESULTS_REQUEST';
export const FETCH_POLL_RESULTS_SUCCESS = 'FETCH_POLL_RESULTS_SUCCESS';
export const FETCH_POLL_RESULTS_FAILURE = 'FETCH_POLL_RESULTS_FAILURE';
