export const FETCH_POLLS_REQUEST = 'FETCH_POLLS_REQUEST';
export const FETCH_POLLS_SUCCESS = 'FETCH_POLLS_SUCCESS';
export const FETCH_POLLS_FAILURE = 'FETCH_POLLS_FAILURE';

export const FETCH_NEW_POLLS_REQUEST = 'FETCH_NEW_POLLS_REQUEST';
export const FETCH_NEW_POLLS_SUCCESS = 'FETCH_NEW_POLLS_SUCCESS';
export const FETCH_NEW_POLLS_FAILURE = 'FETCH_NEW_POLLS_FAILURE';

export const CREATE_POLL_REQUEST = 'CREATE_POLL_REQUEST';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const CREATE_POLL_FAILURE = 'CREATE_POLL_FAILURE';
