export const FETCH_ANNOUNCEMENTS_REQUEST = 'FETCH_ANNOUNCEMENTS_REQUEST';
export const FETCH_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_ANNOUNCEMENTS_FAILURE = 'FETCH_ANNOUNCEMENTS_FAILURE';

export const FETCH_NEW_ANNOUNCEMENTS_REQUEST = 'FETCH_NEW_ANNOUNCEMENTS_REQUEST';
export const FETCH_NEW_ANNOUNCEMENTS_SUCCESS = 'FETCH_NEW_ANNOUNCEMENTS_SUCCESS';
export const FETCH_NEW_ANNOUNCEMENTS_FAILURE = 'FETCH_NEW_ANNOUNCEMENTS_FAILURE';

export const FETCH_OLD_ANNOUNCEMENTS_REQUEST = 'FETCH_OLD_ANNOUNCEMENTS_REQUEST';
export const FETCH_OLD_ANNOUNCEMENTS_SUCCESS = 'FETCH_OLD_ANNOUNCEMENTS_SUCCESS';
export const FETCH_OLD_ANNOUNCEMENTS_FAILURE = 'FETCH_OLD_ANNOUNCEMENTS_FAILURE';

export const CREATE_ANNOUNCEMENT_REQUEST = 'CREATE_ANNOUNCEMENT_REQUEST';
export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS';
export const CREATE_ANNOUNCEMENT_FAILURE = 'CREATE_ANNOUNCEMENT_FAILURE';
